"""empty message

Revision ID: eeb155ebb263
Revises: 4ba0d279d1d4
Create Date: 2025-09-13 23:18:47.809563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eeb155ebb263"
down_revision: Union[str, Sequence[str], None] = "4ba0d279d1d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Bookings", sa.Column("date_from", sa.Date(), nullable=False))
    op.drop_column("Bookings", "date_frome")
    op.drop_column("Bookings", "total_cost")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Bookings",
        sa.Column(
            "total_cost",
            sa.INTEGER(),
            sa.Computed("(price * (date_to - date_frome))", persisted=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "Bookings",
        sa.Column("date_frome", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("Bookings", "date_from")
    # ### end Alembic commands ###
