"""empty message

Revision ID: e0b616b742e1
Revises: 1e8a6e980750
Create Date: 2025-09-12 21:46:11.015820

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b616b742e1"
down_revision: Union[str, Sequence[str], None] = "1e8a6e980750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Bookings", sa.Column("create_at", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Bookings", "create_at")
    # ### end Alembic commands ###
