"""empty message

Revision ID: f5e8932bb982
Revises: 98ed3d834142
Create Date: 2025-09-11 19:27:08.867411

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5e8932bb982"
down_revision: Union[str, Sequence[str], None] = "98ed3d834142"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("Bookings_room_id_fkey"), "Bookings", type_="foreignkey")
    op.create_foreign_key(None, "Bookings", "Rooms", ["room_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Bookings", type_="foreignkey")
    op.create_foreign_key(
        op.f("Bookings_room_id_fkey"), "Bookings", "Bookings", ["room_id"], ["id"]
    )
    # ### end Alembic commands ###
