"""empty message

Revision ID: 1e8a6e980750
Revises: 69e0c84d6bb4
Create Date: 2025-09-12 20:47:47.413930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e8a6e980750"
down_revision: Union[str, Sequence[str], None] = "69e0c84d6bb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Bookings",
        sa.Column(
            "total_cost",
            sa.Integer(),
            sa.Computed(
                "price * (date_to - date_frome)",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Bookings", "total_cost")
    # ### end Alembic commands ###
