"""empty message

Revision ID: 69e0c84d6bb4
Revises: f5e8932bb982
Create Date: 2025-09-11 19:28:25.264610

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "69e0c84d6bb4"
down_revision: Union[str, Sequence[str], None] = "f5e8932bb982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
