"""empty message

Revision ID: 1e03be4c749d
Revises: 20645a52a430
Create Date: 2025-09-09 18:07:40.541052

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e03be4c749d"
down_revision: Union[str, Sequence[str], None] = "20645a52a430"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "Users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Users", type_="unique")
    # ### end Alembic commands ###
